/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import backend.service.nhanVienService;
import backend.viewmodel.nhanVienViewModel;
import java.awt.Window;
import java.util.ArrayList;
import java.util.EventListener;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VHC
 */
public class ChonNVVanChuyen extends javax.swing.JPanel {

    private List<nhanVienViewModel> listNV = new ArrayList<>();
    private DefaultTableModel dtmNV = new DefaultTableModel();
    private nhanVienService srNV = new nhanVienService();

    interface nhanVienSelectedListener extends EventListener {

        void nhanVienSelected(String sdtChon, String tenNV);
    };
    
    private List<nhanVienSelectedListener> listeners = new ArrayList<>();
    private String sdtChon;
    private String tenNVChon;

    public String getSdtChon() {
        return sdtChon;
    }

    public String getTenNVChon() {
        return tenNVChon;
    }
    
    
    /**
     * Creates new form ChonNVVanChuyen
     */
    public ChonNVVanChuyen() {
        initComponents();
        listNV = srNV.getAll();
        dtmNV = (DefaultTableModel) tblNV.getModel();
        showDataTable(listNV);
    }

    public void showDataTable(List<nhanVienViewModel> lists) {
        dtmNV.setRowCount(0);
        int i = 1;
        for (nhanVienViewModel list : lists) {
            dtmNV.addRow(new Object[]{
                i++,
                list.getMaNV(),
                list.getTenNV(),
                list.isGioiTinh() ? "Nam" : "Nữ",
                list.getSDT(),
                list.getCCCD(),
                list.getTenChucVu(),
                list.getNgaySinh(),
                list.getEmail(),
                list.getTrangThai(),});
        }
    }
    
    // Phương thức để đăng ký lắng nghe cho sự kiện chọn khách hàng
    public void addNhanVienSelectedListener(nhanVienSelectedListener listener) {
        listeners.add(listener);
    }

    // Phương thức để thông báo cho tất cả các lắng nghe về sự kiện rằng một khách hàng đã được chọn
    private void fireNhanVienSelectedEvent(String sdt, String tenKhachHang) {
        for (nhanVienSelectedListener listener : listeners) {
            listener.nhanVienSelected(sdtChon, tenNVChon);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new textfield.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNV = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(534, 271));

        txtSearch.setLabelText("Tìm kiếm");

        tblNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NV", "Tên NV", "Giới tính", "SDT", "CCCD", "Chức vụ", "Ngày sinh", "Email"
            }
        ));
        tblNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNV);

        jButton1.setText("Chọn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNVMouseClicked
        //        int selectedRow = tblKH.getSelectedRow();
        //        if (selectedRow != -1) {
        //            // Lấy mã và tên khách hàng từ hàng được chọn trong bảng
        //            maKhachHangChon = tblKH.getValueAt(selectedRow, 1).toString();
        //            tenKhachHangChon = tblKH.getValueAt(selectedRow, 2).toString();
        //            System.out.println(maKhachHangChon + tenKhachHangChon);
        //        }
    }//GEN-LAST:event_tblNVMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // Lấy thông tin mã và tên khách hàng từ hàng được chọn trong bảng
        int selectedRow = tblNV.getSelectedRow();
        if (selectedRow != -1) {
            sdtChon = tblNV.getValueAt(selectedRow, 4).toString();
            tenNVChon = tblNV.getValueAt(selectedRow, 2).toString();

            // Thông báo cho các lắng nghe về sự kiện rằng một khách hàng đã được chọn
            fireNhanVienSelectedEvent(sdtChon, tenNVChon);
        }

        Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JFrame) {
            ((JFrame) window).dispose();
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNV;
    private textfield.TextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
