/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import backend.service.HDCTService;
import backend.viewmodel.HDCTViewModel;
import java.awt.Window;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VHC
 */
public class SuaGioHang extends javax.swing.JPanel {

    /**
     * Creates new form SuaGioHang
     */
    private List<HDCTViewModel> listGH = new ArrayList<>();
    private HDCTService srGH = new HDCTService();
    private DefaultTableModel dtmGH = new DefaultTableModel();
    private NumberFormat currencyFormat = new DecimalFormat("###,###,### VND");
    private int idHD;
    private BanHang parentBanHang;

    public SuaGioHang(BanHang parentBanHang, int idHD) {
        initComponents();
        this.idHD = idHD;
        this.parentBanHang = parentBanHang;
        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = srGH.getAll(this.idHD);
        showDataGH();
    }

    private void showDataGH() {
        dtmGH.setRowCount(0);
        int i = 1;
        for (HDCTViewModel hdct : listGH) {
            dtmGH.addRow(new Object[]{
                i++,
                "SPCT-" + hdct.getMaSPCT(),
                hdct.getTenSP(),
                hdct.getMauSac(),
                hdct.getSize(),
                hdct.getChatLieu(),
                hdct.getThuongHieu(),
                hdct.getSoLuong(),
                currencyFormat.format(hdct.getGiaBan()),
                currencyFormat.format(hdct.getSoLuong() * hdct.getGiaBan())
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblGH = new javax.swing.JTable();
        btnXacNhan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        tblGH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SPCT", "Tên SP", "Màu sắc", "Size", "Chất liệu", "Thương Hiệu", "Số lượng", "Giá bán", "Thành tiền"
            }
        ));
        tblGH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGH);

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Giỏ hàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnXacNhan)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JFrame) {
            ((JFrame) window).dispose(); // Đóng cửa sổ SuaGioHang sau khi xác nhận
        }
        if (parentBanHang != null) {
            parentBanHang.refreshGioHang();
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void tblGHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGHMouseClicked
        int selectedRow = tblGH.getSelectedRow();
        HDCTViewModel hdct = listGH.get(selectedRow);
        int idSPCT = hdct.getMaSPCT();
        if (selectedRow != -1) { // Kiểm tra xem có hàng nào được chọn không
            String currentQuantityStr = dtmGH.getValueAt(selectedRow, 7).toString(); // Lấy số lượng hiện tại từ cột số lượng (cột thứ 7)
            int currentQuantity = Integer.parseInt(currentQuantityStr); // Chuyển đổi số lượng hiện tại từ chuỗi sang số nguyên

            String newQuantityStr = JOptionPane.showInputDialog(this, "Nhập số lượng mới:"); // Hiển thị hộp thoại đầu vào và lấy số lượng mới từ người dùng
            if (newQuantityStr != null && !newQuantityStr.isEmpty()) { // Kiểm tra xem người dùng đã nhập số lượng mới hay không
                try {
                    int newQuantity = Integer.parseInt(newQuantityStr); // Chuyển đổi số lượng mới từ chuỗi sang số nguyên
                    if (newQuantity == 0) { // Kiểm tra xem số lượng mới có hợp lệ không
                        srGH.deleteHDCT(idHD,newQuantity, idSPCT);
                        listGH = srGH.getAll(idHD);
                        showDataGH();
                    } else if (newQuantity > 0) {
                        srGH.updateHDCT(idHD, newQuantity, idSPCT);
                        listGH = srGH.getAll(idHD);
                        showDataGH();
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập một số nguyên dương."); // Thông báo lỗi nếu không thể chuyển đổi số lượng mới sang số nguyên
                }
            }
        }
    }//GEN-LAST:event_tblGHMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGH;
    // End of variables declaration//GEN-END:variables
}
